### PR TITLE
[DATAFU-148] Spark Support

### PR DESCRIPTION
**Pull request by uzadude**
Creating this PR to consolidate all the realted changes to first version that supports Spark.
[DATAFU-148](https://issues.apache.org/jira/browse/DATAFU-148)

### CODE REVIEW

**Comment by uzadude** [comment]
Copy of comments from Jira:

In SparkDFUtils.scala:
 - dedup2 could use some additional description to differentiate it from dedup.
flatten is missing documentation
- for broadcastJoinSkewed, the description of the numberCustsToBroadcast field isn't clear to me
- joinWithRange could use some more documentation. For example, the fields are not all documented. It's not immediately obvious to me what DECREASE_FACTOR does and why it should have a default value of 2^8.
- Also, joinWithRange seems characteristically different from the other in this file, as it's a bit more use-case specific. Maybe later it would make sense to move this to a separate file.

**Comment by uzadude** [comment]
@matthayes , @eyala - I've fixed according to your comments.

**Comment by uzadude** [comment]
wrong base

**Comment by uzadude** [comment]
re-opening after adding ScalaPythonBridge functionallity

**Comment by eyala** [comment]
Merged the commit from Feb 18th

**Pull request closed without merging**
