### PR TITLE
DATAFU-162: Upgraded to log4j2 in datafu-spark

### PR DESCRIPTION
**Pull request by arpitbhardwaj**
Upgraded Log4j version from Log4j1 (1.2.17) to Log4j2 (2.19.0) in datafu-spark.

JIRA: [DATAFU-162](https://issues.apache.org/jira/browse/DATAFU-162)
Refer: https://logging.apache.org/log4j/2.x/manual/migration.html

### CODE REVIEW

**Comment by eyala** [comment]
It seems to me like there are some changes in what is being logged. You can see this by comparing the gradle build results in _datafu-spark/build/test-results_ (between the master branch and yours).

For example, this line is missing in DataframeOpsTests:

`WARN apache.spark.SparkContext - Using an existing SparkContext; some configuration may not take effect.
`

And some messages with level _WARN hive.metastore.ObjectStore_ from TestScalaPythonBridge, and _WARN hive.metastore.ObjectStore_ from UdafTests.

If it's just the default logging level in the tests, I think it's fine ... but if it will lead to a change in actual usage then less so.

**Comment by arpitbhardwaj** [comment]
ok let me check the cause for missing lines

**Comment by arpitbhardwaj** [comment]
@eyala Thanks for pointing it out. 

Found the cause it was happening due to missing log4j2 properties in test resources. 
I have added it now and removed the older one. 

Logger lines are now as it is master. Please verify and let me know.

**Comment by eyala** [comment]
Hi @arpitbhardwaj , looks good.

Did you see what I wrote about adding your email to your GitHub account? I do want your last commit to be included on your profile. At any rate, I will merge this one as it is, so the PR itself gets counted.

**Comment by arpitbhardwaj** [comment]
@eyala Yes i corrected the email in this PR commit. In last PR commit there was some other email got attached wrongly.

**Pull request merged**
